auto: true
server: true
permalink: none
baseurl: "http://rvondohlen.github.com/prepare/"
exclude:
- .gitignore

prose:
  rooturl: "_posts"
  metadata: 
    _posts/recipes: |
      published: false
      layout: recipe
      title: Title of Recipe
      tags: tag
      author_twitter: ryanvondohlen
      author: Ryan von Dohlen
      categories:
      - recipes
